insert into Transport(tName,tType, fuel,unit,region,efFactor)
values
('CNG - Euro 6 and later 4', 'Passenger Cars','CNG','g/km','NA',0.398 ),
('CNG - Euro 4 and 5&6', 'Passenger Cars','CNG','g/km','NA',0.398 ),
('E85 - Euro 4 and later', 'Passenger Cars','E85','g/km','NA',0.398 ),
('Hybrid Petrol Large - Euro 4 and later', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Hybrid Petrol Medium - Euro 4 and later', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Diesel Small - Euro 6 up to 2016', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Small - Euro 6 2017-2023', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Small - Euro 6 2020+', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Petrol Large-SUV-Executive - Euro 6 2020+', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Diesel Small - Euro 4 - 98/69/EC II', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Small - Euro 5 – EC 715/2007', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Medium - Euro 4 - 98/69/EC II', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Medium - Euro 3 - 98/69/EC I', 'Passenger Cars','Diesel','g/km','NA',0.464 ),
('Petrol Large-SUV-Executive - Euro 6 up to 2016', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Diesel Medium - Conventional', 'Passenger Cars','Diesel','g/km','NA',0.663 ),
('Diesel Medium - Euro 2 - 94/12/EEC', 'Passenger Cars','Diesel','g/km','NA',0.53 ),
('Diesel Medium - Euro 1 - 91/441/EEC', 'Passenger Cars','Diesel','g/km','NA',0.596 ),
('Petrol Large-SUV-Executive - ECE 15/04', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Large-SUV-Executive - Euro 1 - 91/441/EEC', 'Passenger Cars','Petrol','g/km','NA',0.596 ),
('Petrol Large-SUV-Executive - ECE 15/00-01', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Large-SUV-Executive - ECE 15/02', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Large-SUV-Executive - ECE 15/03', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Diesel Medium - Euro 6 up to 2016', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Petrol Large-SUV-Executive - Euro 2 - 94/12/EEC', 'Passenger Cars','Petrol','g/km','NA',0.53 ),
('Petrol Large-SUV-Executive - Euro 6 2017-2023', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Large-SUV-Executive - Euro 3 - 98/69/EC I', 'Passenger Cars','Petrol','g/km','NA',0.464 ),
('Petrol Large-SUV-Executive - Euro 5 – EC 715/2007', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Large-SUV-Executive - Euro 4 - 98/69/EC II', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('LPG - Euro 1 - 91/441/EEC', 'Passenger Cars','LPG','g/km','NA',0.596 ),
('LPG - Euro 2 - 94/12/EEC', 'Passenger Cars','LPG','g/km','NA',0.53 ),
('Diesel Large-SUV-Executive - Euro 6 2020+', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Large-SUV-Executive - Euro 6 2017-2023', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('LPG - Conventional', 'Passenger Cars','LPG','g/km','NA',0.663 ),
('LPG - Euro 6 – EC 715/2007', 'Passenger Cars','LPG','g/km','NA',0.398 ),
('Hybrid Petrol Small - Euro 4 and later', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('LPG - Euro 4 - 98/69/EC II', 'Passenger Cars','LPG','g/km','NA',0.398 ),
('LPG - Euro 5 – EC 715/2007', 'Passenger Cars','LPG','g/km','NA',0.398 ),
('LPG - Euro 3 - 98/69/EC I', 'Passenger Cars','LPG','g/km','NA',0.464 ),
('Diesel Medium - Euro 6 2020+', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Large-SUV-Executive - Conventional', 'Passenger Cars','Diesel','g/km','NA',0.663 ),
('Petrol Medium - Euro 6 2020+', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Diesel Medium - Euro 5 – EC 715/2007', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Medium - Euro 6 2017-2023', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Large-SUV-Executive - Euro 4 - 98/69/EC II', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Large-SUV-Executive - Euro 6 up to 2016', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Large-SUV-Executive - Euro 5 – EC 715/2007', 'Passenger Cars','Diesel','g/km','NA',0.398 ),
('Diesel Large-SUV-Executive - Euro 2 - 94/12/EEC', 'Passenger Cars','Diesel','g/km','NA',0.53 ),
('Diesel Large-SUV-Executive - Euro 3 - 98/69/EC I', 'Passenger Cars','Diesel','g/km','NA',0.464 ),
('Diesel Large-SUV-Executive - Euro 1 - 91/441/EEC', 'Passenger Cars','Diesel','g/km','NA',0.596 ),
('Petrol Mini - Euro 6 2020+', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Small - PRE ECE', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Mini - Euro 6 up to 2016', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Mini - Euro 5 – EC 715/2007', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Mini - Euro 6 2017-2023', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Small - ECE 15/04', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Small - Euro 1 - 91/441/EEC', 'Passenger Cars','Petrol','g/km','NA',0.596 ),
('Petrol Small - Open Loop', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Small - ECE 15/02', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Small - ECE 15/03', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Small - ECE 15/00-01', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('', 'All vehicles type','Petrol','kg/kg fuel','NA',3.18 ),
('', 'All vehicles type','Petrol','kg/kg fuel','NA',3.18 ),
('', 'All vehicles type','Petrol','kg/kg fuel','NA',3.18 ),
('', 'All vehicles type','Diesel','kg/kg fuel','NA',3.14 ),
('', 'All vehicles type','E85 4','kg/kg fuel','NA',2.104 ),
('', 'All vehicles type','E85 4','kg/kg fuel','NA',2.104 ),
('', 'All vehicles type','E85 4','kg/kg fuel','NA',2.104 ),
('', 'All vehicles type','Petrol','kg/kg fuel','NA',3.18 ),
('', 'All vehicles type','E10 4','kg/kg fuel','NA',3.061 ),
('Petrol Mini - Euro 4 - 98/69/EC II', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('', 'All vehicles type','CNG3(or LNG)','kg/kg fuel','NA',2.75 ),
('', 'All vehicles type','Diesel','kg/kg fuel','NA',3.14 ),
('', 'All vehicles type','Diesel','kg/kg fuel','NA',3.14 ),
('', 'All vehicles type','LPG2','kg/kg fuel','NA',3.017 ),
('', 'All vehicles type','LPG2','kg/kg fuel','NA',3.017 ),
('', 'All vehicles type','LPG2','kg/kg fuel','NA',3.017 ),
('', 'All vehicles type','LPG2','kg/kg fuel','NA',3.017 ),
('', 'All vehicles type','E85 4','kg/kg fuel','NA',2.104 ),
('', 'All vehicles type','CNG3(or LNG)','kg/kg fuel','NA',2.75 ),
('', 'All vehicles type','E10 4','kg/kg fuel','NA',3.061 ),
('', 'All vehicles type','CNG3(or LNG)','kg/kg fuel','NA',2.75 ),
('', 'All vehicles type','E5 4','kg/kg fuel','NA',3.125 ),
('', 'All vehicles type','E5 4','kg/kg fuel','NA',3.125 ),
('', 'All vehicles type','E5 4','kg/kg fuel','NA',3.125 ),
('', 'All vehicles type','E5 4','kg/kg fuel','NA',3.125 ),
('', 'All vehicles type','E10 4','kg/kg fuel','NA',3.061 ),
('', 'All vehicles type','E10 4','kg/kg fuel','NA',3.061 ),
('', 'All vehicles type','Diesel','kg/kg fuel','NA',3.14 ),
('', 'All vehicles type','CNG3(or LNG)','kg/kg fuel','NA',2.75 ),
('Petrol Medium - Euro 2 - 94/12/EEC', 'Passenger Cars','Petrol','g/km','NA',0.53 ),
('Petrol Medium - Euro 3 - 98/69/EC I', 'Passenger Cars','Petrol','g/km','NA',0.464 ),
('Petrol Medium - Open Loop', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Medium - ECE 15/04', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Medium - Euro 1 - 91/441/EEC', 'Passenger Cars','Petrol','g/km','NA',0.596 ),
('Petrol Medium - Euro 6 2017-2023', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Large-SUV-Executive - PRE ECE', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Medium - Euro 5 – EC 715/2007', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Medium - Euro 6 up to 2016', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Medium - Euro 4 - 98/69/EC II', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Small - Euro 5 – EC 715/2007', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Small - Euro 6 up to 2016', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Small - Euro 3 - 98/69/EC I', 'Passenger Cars','Petrol','g/km','NA',0.464 ),
('Petrol Small - Euro 2 - 94/12/EEC', 'Passenger Cars','Petrol','g/km','NA',0.53 ),
('Petrol Small - Euro 4 - 98/69/EC II', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Medium - ECE 15/00-01', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Medium - ECE 15/03', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Medium - ECE 15/02', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Small - Euro 6 2020+', 'Passenger Cars','Petrol','g/km','NA',0.398 ),
('Petrol Medium - PRE ECE', 'Passenger Cars','Petrol','g/km','NA',0.663 ),
('Petrol Small - Euro 6 2017-2023', 'Passenger Cars','Petrol','g/km','NA',0.398 )